# Generated by Django 4.1.6 on 2023-05-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_alter_article_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_visit', models.PositiveIntegerField(default=0, verbose_name='浏览量')),
            ],
        ),
    ]
