# Generated by Django 4.1.6 on 2023-05-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_articlevisit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleVisit',
        ),
        migrations.AddField(
            model_name='article',
            name='total_visit',
            field=models.PositiveIntegerField(default=0, verbose_name='浏览量'),
        ),
    ]
