# Generated by Django 4.1.6 on 2023-05-10 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_delete_articlevisit_article_total_visit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created', '-updated'], 'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
    ]
