# Generated by Django 4.1.6 on 2023-05-11 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_articlecolumn_article_column'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecolumn',
            options={'verbose_name': '专栏', 'verbose_name_plural': '专栏'},
        ),
        migrations.AlterField(
            model_name='article',
            name='column',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article', to='article.articlecolumn', verbose_name='专栏'),
        ),
    ]
