# Generated by Django 4.1.6 on 2023-05-19 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_article_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='total_comment',
            field=models.PositiveIntegerField(default=0, verbose_name='评论条数'),
        ),
    ]
