# Generated by Django 4.1.6 on 2023-05-24 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_alter_article_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='column',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article', to='article.articlecolumn', verbose_name='专栏'),
        ),
        migrations.AlterField(
            model_name='articlecolumn',
            name='title',
            field=models.CharField(max_length=60, verbose_name='专栏名称'),
        ),
    ]
