# Generated by Django 4.1.6 on 2023-05-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userprofile_biography'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=' avatar/%Y%m%d/', verbose_name='头像'),
        ),
    ]
